
##################################################################################################
# Service Template
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  {{- range $v := .Values.service_list }}
  name: {{ .Values.service_list.name }}
  labels:
    app: {{ .Values.service_list.name }}
    service: {{ .Values.service_list.name }}
spec:
  ports:
  - port: {{ .Values.service_list.port }}
    name: {{ .Values.service_list.protocol }}
  selector:
    app: {{ .Values.service_list.name }}
  {{- end }}    
---
