apiVersion: v1
kind: Service
metadata:
  name: apache-demo-service
  labels:
    app: apache_demo_app
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
  selector:
    app: apache_demo_app